### ISSUE TITLE
`bundle exec rackup` fails

### ISSUE THREAD

**Issue by joppiesaus** [neocities/neocities#224]
Hi, I'm trying to [write a fix for a bug](https://github.com/neocities/neocities/issues/215#issuecomment-238352627), but I want to be able to test if my code is correct and fixes the bug.

I did the thing in `README.md`,
```sh
vagrant up --provision
vagrant ssh
cd /vagrant
bundle exec rackup
```
But that fails, I need to specify a config, but I've no idea how to do that!

I've tried:
```sh
cp config.yml.template config.yml
bundle exec rackup
```
But that returns this: :rage1: 
```
bundle exec rackup
/var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/adapters/postgres.rb:216:in `initialize': PG::ConnectionBad: fe_sendauth: no password supplied (Sequel::DatabaseConnectionError)
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/adapters/postgres.rb:216:in `new'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/adapters/postgres.rb:216:in `connect'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool.rb:96:in `make_new'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:158:in `make_new'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:137:in `available'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:127:in `block in acquire'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:194:in `block in sync'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:194:in `synchronize'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:194:in `sync'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:126:in `acquire'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/connection_pool/threaded.rb:94:in `hold'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/database/connecting.rb:229:in `synchronize'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/adapters/shared/postgres.rb:442:in `server_version'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/adapters/shared/postgres.rb:458:in `supports_create_table_if_not_exists?'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/database/schema_methods.rb:196:in `create_table?'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/extensions/migration.rb:585:in `schema_dataset'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/extensions/migration.rb:443:in `initialize'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/extensions/migration.rb:505:in `initialize'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/extensions/migration.rb:390:in `new'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/extensions/migration.rb:390:in `run'
	from /var/lib/gems/2.2.0/gems/sequel-4.8.0/lib/sequel/extensions/migration.rb:361:in `apply'
	from /vagrant/environment.rb:100:in `<top (required)>'
	from /vagrant/app.rb:1:in `require'
	from /vagrant/app.rb:1:in `<top (required)>'
	from /vagrant/config.ru:2:in `require'
	from /vagrant/config.ru:2:in `block in <main>'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /vagrant/config.ru:in `new'
	from /vagrant/config.ru:in `<main>'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /var/lib/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	from /usr/local/bin/rackup:23:in `load'
	from /usr/local/bin/rackup:23:in `<main>'
```

Can somebody help me? I have no clue where to go from here... :confused: I'm trying to be useful! :heart:

**Comment by kyledrake** [comment]
I've committed some changes to bring the vagrant support up to date. You should run vagrant destroy and re-run the vagrant installer. You'll need to use the new config.yml.template.

You'll also need to start with this command now: bundle exec rackup -o 0.0.0.0

Apologies for the issues, the Vagrantfile gets stale from time to time.
