### ISSUE TITLE
Certificate verify failed with the neocities cli client

### ISSUE THREAD

**Issue by janseeger** [neocities/neocities#395]
I have a GitLab Pipelines deployment where the pages get rendered and in a second stage the content is pushed to neocities using the official client.

Today I noticed that it fails to connect to the Neocities API (https://neocities.org/api), which on my local machine is signed with a valid Let's Encrypt Cert that will expire on Friday, 29. July 2022:

```
Using docker image sha256:c643bcc7be255e008e0a12520c8e48ff863ce01e037a467dbe5e7709f9b21540 for registry.gitlab.com/***** with digest registry.gitlab.com/***** ...
$ if [ -z "$NEOCITIES_TOKEN" ]; then echo No Neocities API token && false; else mkdir -p $HOME/.config/neocities && mv $NEOCITIES_TOKEN $HOME/.config/neocities/config; fi
$ cd _site
$ neocities push .
/var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `ssl_connect'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:41:in `initialize'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `new'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `create_socket'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
	from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /var/lib/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/client.rb:86:in `post'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/client.rb:42:in `upload_hash'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/client.rb:54:in `upload'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/cli.rb:225:in `block (2 levels) in push'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/cli.rb:222:in `each'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/cli.rb:222:in `block in push'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/cli.rb:191:in `chdir'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/cli.rb:191:in `push'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/lib/neocities/cli.rb:79:in `run'
	from /var/lib/gems/2.7.0/gems/neocities-0.0.15/bin/neocities:4:in `<top (required)>'
	from /usr/local/bin/neocities:23:in `load'
	from /usr/local/bin/neocities:23:in `<main>'
Uploading tag/ios/index.html ... 

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

For reference, here's the Dockerfile for the image:
```
FROM debian:stable-slim
RUN apt-get update && apt-get install -y \
  ruby \
  --no-install-recommends \
 && apt-get autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN gem install -V --no-document \
  rake \
  neocities
```

**Comment by kyledrake** [comment]
I've pushed 0.0.16 of the gem which uses a monkeypatched httpclient to use the system certs instead of the embedded ones, and  assuming the ruby/os environment isn't too crazy this should fix the problem, could you try bumping to the new version and trying it?

**Comment by janseeger** [comment]
With 0.0.16 it seems to work. Thank you that was really fast!
