### ISSUE TITLE
Charts have stopped working

### ISSUE THREAD

**Issue by em-777** [neocities/neocities#481]
When I go to a site's statistics, I notice that the view chart no longer shows up. This error shows up in the console:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed 
source of script in the following Content Security Policy directive: "script-src 'self' blob: 'unsafe-inline' 
https://hcaptcha.com https://*.hcaptcha.com https://js.stripe.com".

    at new Function (<anonymous>)
    at e (Chart.min.js:10:4678)
    at s.template (Chart.min.js:10:5069)
    at e.buildYLabels (Chart.min.js:10:19896)
    at e.fit (Chart.min.js:10:20462)
    at e.initialize (Chart.min.js:10:19781)
    at e.Element (Chart.min.js:10:14585)
    at new e (Chart.min.js:10:2748)
    at s.buildScale (Chart.min.js:11:7823)
    at s.<anonymous> (Chart.min.js:11:5726)
```

**Comment by kyledrake** [comment]
Thanks for the report, I've taken care of it and it should be working again.
