### ISSUE TITLE
Try switching to Rubinius

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#83]
[Rubinius](http://rubini.us) is a threaded, modern, correct implementation of Ruby that's threaded and worked on by passionate local friends I have access to that share my ideals regarding the proper engineering and architecture of software.

I have been told that it is pretty stable at this point, and I think they could use some more production stories, so I'm commiting to try a port over to see how well it goes. This allows me to provide feedback if there are issues to help improve the project.

Step one is getting test specs to pass for Rubinius, which I am trying now.

**Comment by brixen** [comment]
@kyledrake awesome! I'll fork and take a look at running the specs.

**Comment by kyledrake** [comment]
I ran the test suite against 2.5.1 and hit a snag with rubysl-rss:

```
~/code/neocities $ be rake
/usr/local/rubinius/bin/rbx -I"lib:spec" -I"/usr/local/rubinius/gems/gems/rake-10.3.2/lib" "/usr/local/rubinius/gems/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "tests/acceptance/admin_tests.rb" "tests/acceptance/dashboard_tests.rb" "tests/acceptance/index_tests.rb" "tests/acceptance/plan_tests.rb" "tests/acceptance/settings/account_tests.rb" "tests/acceptance/settings/site_tests.rb" "tests/acceptance/signin_tests.rb" "tests/acceptance/signup_tests.rb" "tests/acceptance/site_tests.rb" "tests/api_tests.rb" "tests/ext_tests.rb" "tests/site_file_tests.rb" "tests/site_tests.rb" "tests/tag_tests.rb" "tests/workers/email_worker_tests.rb" "tests/workers/screenshot_worker_tests.rb" 
A syntax error has occurred:
    syntax error, unexpected $end: /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore.rb:32:38

Code:
          alias set_dc_titledc_title=
                                     ^

Backtrace:

                                 CodeTools::Melbourne#syntax_error at /usr/local/rubinius/runtime/gems/rubinius-melbourne-2.3.0.0/lib/rubinius
                                                                      /melbourne.rbc:48
                                 CodeTools::Melbourne#parse_string at /usr/local/rubinius/runtime/gems/rubinius-melbourne-2.3.0.0/lib/rubinius
                                                                      /melbourne.rbc:52
 CodeTools::Compiler::StringParser(CodeTools::Compiler::EvalParser)#parse at /usr/local/rubinius/runtime/gems/rubinius-compiler-2.3.0/lib/rubinius
                                                                             /compiler/stages.rbc:241
  CodeTools::Compiler::Parser(CodeTools::Compiler::EvalParser)#run at /usr/local/rubinius/runtime/gems/rubinius-compiler-2.3.0/lib/rubinius
                                                                      /compiler/stages.rbc:207
                                           CodeTools::Compiler#run at /usr/local/rubinius/runtime/gems/rubinius-compiler-2.3.0/lib/rubinius
                                                                      /compiler/compiler.rbc:361
                                  CodeTools::Compiler.compile_eval at /usr/local/rubinius/runtime/gems/rubinius-compiler-2.3.0/lib/rubinius
                                                                      /compiler/compiler.rbc:305
                               CodeTools::Compiler.construct_block at /usr/local/rubinius/runtime/gems/rubinius-compiler-2.3.0/lib/rubinius
                                                                      /compiler/compiler.rbc:317
                                          Module(Class)#module_eval at kernel/common/eval.rb:219
            { } in RSS::BaseDublinCoreModel(Module)#append_features at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore.rb:20
                                                         Array#each at kernel/bootstrap/array.rb:76
                   RSS::BaseDublinCoreModel(Module)#append_features at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore.rb:12
                                       { } in Module(Class)#include at kernel/delta/module.rb:98
                                                 Array#reverse_each at kernel/common/array.rb:1236
                                              Module(Class)#include at kernel/delta/module.rb:92
                                    { } in Object(Class)#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore/1.0.rb:7
                                    { } in Object(Class)#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore/1.0.rb:7
                                   { } in Object(Module)#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore/1.0.rb:6
                                                  Object#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore/1.0.rb:3
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                                  Object#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss/dublincore.rb:159
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                                  Object#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rubysl/rss/rss.rb:83
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                                  Object#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rubysl/rss.rb:1
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                                  Object#__script__ at /usr/local/rubinius/gems/gems/rubysl-rss-2.0.0/lib/rss.rb:1
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                                  Object#__script__ at models/site.rb:2
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                           { } in Object#__script__ at environment.rb:100
                                                         Array#each at kernel/bootstrap/array.rb:76
                                                  Object#__script__ at environment.rb:100
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                                  Object#__script__ at tests/environment.rb:13
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                              Rubinius::CodeLoader.require_relative at kernel/common/code_loader.rb:147
                                    Kernel(Object)#require_relative at kernel/common/kernel.rb:761
                                                  Object#__script__ at tests/acceptance/environment.rb:1
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                              Rubinius::CodeLoader.require_relative at kernel/common/code_loader.rb:147
                                    Kernel(Object)#require_relative at kernel/common/kernel.rb:761
                                                  Object#__script__ at tests/acceptance/admin_tests.rb:1
                                       Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
                                             Kernel(Object)#require at kernel/common/kernel.rb:755
                                           { } in Object#__script__ at /usr/local/rubinius/gems/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:15
                                  { } in Enumerable(Array)#find_all at kernel/common/enumerable.rb:465
                                                         Array#each at kernel/bootstrap/array.rb:76
                                Enumerable(Array)#select (find_all) at kernel/common/enumerable.rb:463
                                                  Object#__script__ at /usr/local/rubinius/gems/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4
                                   Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
                                   Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
                                            Rubinius::Loader#script at kernel/loader.rb:655
                                              Rubinius::Loader#main at kernel/loader.rb:809
Warning: coverage data provided by Coverage [130] exceeds number of lines in /home/kyle/code/neocities/environment.rb [25]
Warning: coverage data provided by Coverage [2] exceeds number of lines in /home/kyle/code/neocities/ext/NilClass.rb [1]
Warning: coverage data provided by Coverage [54] exceeds number of lines in /home/kyle/code/neocities/ext/numeric.rb [7]
Warning: coverage data provided by Coverage [3] exceeds number of lines in /home/kyle/code/neocities/ext/phantomjs.rb [1]
Warning: coverage data provided by Coverage [3] exceeds number of lines in /home/kyle/code/neocities/ext/sequel/plugins/create_timestamp.rb [1]
Warning: coverage data provided by Coverage [26] exceeds number of lines in /home/kyle/code/neocities/ext/sequel/plugins/paranoid_delete.rb [7]
Warning: coverage data provided by Coverage [3] exceeds number of lines in /home/kyle/code/neocities/ext/sinatra/base.rb [1]
Warning: coverage data provided by Coverage [15] exceeds number of lines in /home/kyle/code/neocities/ext/string.rb [3]
Warning: coverage data provided by Coverage [4] exceeds number of lines in /home/kyle/code/neocities/ext/time.rb [2]
Warning: coverage data provided by Coverage [31] exceeds number of lines in /home/kyle/code/neocities/models/comment.rb [7]
Warning: coverage data provided by Coverage [20] exceeds number of lines in /home/kyle/code/neocities/models/simple_cache.rb [5]
Warning: coverage data provided by Coverage [12] exceeds number of lines in /home/kyle/code/neocities/models/site_change.rb [6]
Coverage report generated for minitest to /home/kyle/code/neocities/tests/coverage. 37 / 44 LOC (84.09%) covered.
Warning: coverage data provided by Coverage [130] exceeds number of lines in /home/kyle/code/neocities/environment.rb [25]
Warning: coverage data provided by Coverage [2] exceeds number of lines in /home/kyle/code/neocities/ext/NilClass.rb [1]
Warning: coverage data provided by Coverage [54] exceeds number of lines in /home/kyle/code/neocities/ext/numeric.rb [7]
Warning: coverage data provided by Coverage [3] exceeds number of lines in /home/kyle/code/neocities/ext/phantomjs.rb [1]
Warning: coverage data provided by Coverage [3] exceeds number of lines in /home/kyle/code/neocities/ext/sequel/plugins/create_timestamp.rb [1]
Warning: coverage data provided by Coverage [26] exceeds number of lines in /home/kyle/code/neocities/ext/sequel/plugins/paranoid_delete.rb [7]
Warning: coverage data provided by Coverage [3] exceeds number of lines in /home/kyle/code/neocities/ext/sinatra/base.rb [1]
Warning: coverage data provided by Coverage [15] exceeds number of lines in /home/kyle/code/neocities/ext/string.rb [3]
Warning: coverage data provided by Coverage [4] exceeds number of lines in /home/kyle/code/neocities/ext/time.rb [2]
Warning: coverage data provided by Coverage [31] exceeds number of lines in /home/kyle/code/neocities/models/comment.rb [7]
Warning: coverage data provided by Coverage [20] exceeds number of lines in /home/kyle/code/neocities/models/simple_cache.rb [5]
Warning: coverage data provided by Coverage [12] exceeds number of lines in /home/kyle/code/neocities/models/site_change.rb [6]
rake aborted!
Command failed with status (1): [ruby -I"lib:spec" -I"/usr/local/rubinius/gems/gems/rake-10.3.2/lib" "/usr/local/rubinius/gems/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "tests/acceptance/admin_tests.rb" "tests/acceptance/dashboard_tests.rb" "tests/acceptance/index_tests.rb" "tests/acceptance/plan_tests.rb" "tests/acceptance/settings/account_tests.rb" "tests/acceptance/settings/site_tests.rb" "tests/acceptance/signin_tests.rb" "tests/acceptance/signup_tests.rb" "tests/acceptance/site_tests.rb" "tests/api_tests.rb" "tests/ext_tests.rb" "tests/site_file_tests.rb" "tests/site_tests.rb" "tests/tag_tests.rb" "tests/workers/email_worker_tests.rb" "tests/workers/screenshot_worker_tests.rb" ]
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/array.rb:76:in `each'
kernel/bootstrap/array.rb:76:in `each'
kernel/bootstrap/array.rb:76:in `each'
kernel/common/kernel.rb:497:in `load'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:655:in `script'
kernel/loader.rb:809:in `main'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

I've got a bunch of higher priority tickets I need to work on this week (got sick so I got pretty stalled), so I will wait for 2.5.3 and then give this another shot and see if this still an issue. We'll get there.
